### ISSUE TITLE
AppImage doesn't work

### ISSUE THREAD

**Issue by NekoNyanners** [NullDev/senpa-io-client#5]
## Bug report

**Description of the bug:** <br>
Can't start the AppImage

**Steps to reproduce:** <br>
How can we reproduce the problem?

- Open terminal
-  Do `./senpa-io-client-portable-linux-x86_64.appimage`

**Expected result:** <br>
It opens the Senpa.io client

**Actual result:** <br>
> permission denied: ./senpa-io-client-portable-linux-x86_64.appimage

**Environment:** <br>
    - Operating system: Linux Mint
    - NodeJS Version: [e.g v18.2.0] (Optional)
    - NPM Version:    [e.g v8.9.0] (Optional)

**Comment by NullDev** [comment]
You probably have to make the AppImage executable first:

$ `chmod +x ./senpa-io-client-portable-linux-x86_64.appimage`

then try it again:

$ `./senpa-io-client-portable-linux-x86_64.appimage`

**Comment by NekoNyanners** [comment]
Oh.... ty
